const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const DATABASE_URL = process.env.DATABASE_URL!;

export { SUPABASE_URL, SUPABASE_KEY, DATABASE_URL };
